__Задание 1. (0.5 балла)__

Мы будем использовать данные соревнования [Home Credit Default Risk](https://www.kaggle.com/c/home-credit-default-risk/data).  

* Загрузите таблицу **application_train.csv**;
* Запишите в Y столбец с целевой переменной;
* Удалите ненужные столбцы (для этого воспользуйтесь описанием);
* Определите тип столбцов и заполните пропуски - стратегия произвольная;
* Разбейте выборку в соотношении 70:30 с random_state=0.

Так как в данных значительный дисбаланс классов, в качестве метрики качества везде будем использовать площадь под precision-recall кривой.

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Загрузка данных
data = pd.read_csv("application_train.csv")

# Запись целевой переменной
Y = data['TARGET']

# Удаление ненужных столбцов (например, 'SK_ID_CURR')
data = data.drop(columns=['SK_ID_CURR'])

# Вывод информации о столбцах и их типах
data.info()

column_object = []
column_category = []
column_features = []


# Заполнение пропусков (стратегия может быть произвольной)
# К примеру, для числовых значений можно использовать среднее, для категориальных - самый частый элемент.
for column in data.columns:
    if data[column].nunique() < 10:
        data[column] = data[column].astype('category')
        column_category.append(column)
    if data[column].dtype == 'object':
        # Заполнение категориальных пропусков
        data[column].fillna(data[column].mode()[0], inplace=True)
        column_object.append(column)
    elif data[column].dtype != 'category':
        # Заполнение числовых пропусков
        data[column].fillna(data[column].mean(), inplace=True)
        column_features.append(column)

from sklearn.model_selection import train_test_split

# Разделение выборок
X_train_full, X_test_full, y_train, y_test = train_test_split(data, Y, test_size=0.3, random_state=0)

X_train_object, X_train_features = pd.DataFrame(X_train_full[column_object + column_category]), pd.DataFrame(X_train_full[column_features])
X_test_object, X_test_features = pd.DataFrame(X_test_full[column_object + column_category]), pd.DataFrame(X_test_full[column_features])

# X_train_features.info(verbose=True)
# X_train_features.describe(include='all').T
# X_train_features.nunique()
print(np.shape(X_train_features))
X_train_features.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 121 entries, TARGET to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 283.9+ MB
(215257, 66)

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
125587,0,153000.0,104256.0,10440.0,90000.0,0.002042,-22596,365243,-1624.0,-739,3.000000,1.0,9,0.814096,0.562510,0.429424,0.07220,0.100000,0.987600,0.830000,0.000000,0.000000,0.206900,0.166700,0.041700,0.000000,0.058800,0.045500,0.000000,0.176400,0.073500,0.103800,0.987600,0.836700,0.000000,0.00000,0.206900,0.166700,0.041700,0.000000,0.064300,0.047400,0.000000,0.186700,0.07290,0.100000,0.987600,0.832300,0.000000,0.000000,0.206900,0.166700,0.041700,0.000000,0.059900,0.046300,0.000000,0.180100,0.060100,0.0,0.0,0.0,-1500.0,0.0,1.0,0.0
51500,0,427500.0,684000.0,31824.0,684000.0,0.026392,-21545,365243,-8163.0,-3204,12.061091,2.0,13,0.502130,0.704124,0.742182,0.34850,0.088442,0.988100,0.752471,0.044621,0.320000,0.275900,0.375000,0.231894,0.066333,0.100775,0.374900,0.008809,0.069000,0.355000,0.087543,0.988100,0.759637,0.042553,0.32220,0.275900,0.375000,0.228058,0.064958,0.105645,0.390600,0.008076,0.073000,0.35180,0.087955,0.988100,0.755746,0.044595,0.320000,0.275900,0.375000,0.231625,0.067169,0.101954,0.381600,0.008651,0.070400,0.309800,1.0,0.0,1.0,-294.0,0.0,1.0,1.0
276439,0,135000.0,202500.0,10125.0,202500.0,0.018634,-7982,-271,-6383.0,-657,12.061091,1.0,13,0.502130,0.420190,0.394495,0.16390,0.088442,0.979100,0.752471,0.044621,0.078942,0.034500,0.166700,0.231894,0.066333,0.100775,0.045800,0.008809,0.032900,0.167000,0.087543,0.979100,0.759637,0.042553,0.07449,0.034500,0.166700,0.228058,0.064958,0.105645,0.047700,0.008076,0.034800,0.16550,0.087955,0.979100,0.755746,0.044595,0.078078,0.034500,0.166700,0.231625,0.067169,0.101954,0.046600,0.008651,0.033500,0.065400,10.0,1.0,10.0,-202.0,0.0,1.0,2.0
244558,1,270000.0,1502941.5,45567.0,1372500.0,0.072508,-19799,365243,-10227.0,-3334,13.000000,2.0,13,0.502130,0.759615,0.700184,0.15850,0.134600,0.981600,0.748400,0.058000,0.030000,0.198300,0.343800,0.385400,0.000000,0.129200,0.100900,0.000000,0.000600,0.105000,0.055200,0.977700,0.706000,0.036200,0.00000,0.172400,0.166700,0.208300,0.000000,0.091800,0.060600,0.000000,0.000000,0.14310,0.110000,0.977600,0.698100,0.045600,0.000000,0.172400,0.166700,0.208300,0.000000,0.117600,0.100300,0.000000,0.000000,0.166900,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98003,0,180000.0,1288350.0,37800.0,1125000.0,0.018801,-15853,-890,-6605.0,-4397,12.061091,2.0,17,0.502130,0.485956,0.704706,0.11744,0.088442,0.977735,0.752471,0.044621,0.078942,0.149725,0.226282,0.231894,0.066333,0.100775,0.107399,0.008809,0.028358,0.114231,0.087543,0.977065,0.759637,0.042553,0.07449,0.145193,0.222315,0.228058,0.064958,0.105645,0.105975,0.008076,0.027022,0.11785,0.087955,0.977752,0.755746,0.044595,0.078078,0.149213,0.225897,0.231625,0.067169,0.101954,0.108607,0.008651,0.028236,0.102547,0.0,0.0,0.0,-2318.0,0.0,0.0,0.0

__Задание 2. (1.5 балла)__

Также мы будем использовать две реализации градиентного бустинга: [LightGBM](https://lightgbm.readthedocs.io/en/stable/Python-API.html) и [Catboost](https://catboost.ai/en/docs/), которые вам необходимо самостоятельно изучить и установить, используя команды:  
`!pip install lightgb`  
`!pip install catboost`  
Обучите реализации градиентного бустинга LightGBM и Catboost на вещественных признаках без подбора параметров. 
Почему получилась заметная разница в качестве? 

В этом и последующих экспериментах необходимо измерять время обучения моделей.

In [ ]:
# # Отбор только вещественных признаков
# X_train_real = X_train.select_dtypes(include=['float64', 'int64'])
# X_test_real = X_test.select_dtypes(include=['float64', 'int64'])

import time
import lightgbm as lgb
from sklearn.metrics import precision_recall_curve, auc

# Инициализация модели
lgb_model = lgb.LGBMClassifier(verbose=0)

# Измерение времени обучения
start_time = time.time()
lgb_model.fit(X_train_features, y_train)
end_time = time.time()

# Оценка времени
lgb_training_time = end_time - start_time

# Предсказания и оценка качества модели
lgb_pred_probs = lgb_model.predict_proba(X_test_features)[:, 1]
precision, recall, _ = precision_recall_curve(y_test, lgb_pred_probs)
lgb_pr_auc = auc(recall, precision)

print("LightGBM - Время обучения:", lgb_training_time)
print("LightGBM - AUC-PR:", lgb_pr_auc)



from catboost import CatBoostClassifier

# Инициализация модели
cat_model = CatBoostClassifier(verbose=False)

# Измерение времени обучения
start_time = time.time()
cat_model.fit(X_train_features, y_train)
end_time = time.time()

# Оценка времени
cat_training_time = end_time - start_time

# Предсказания и оценка качества модели
cat_pred_probs = cat_model.predict_proba(X_test_features)[:, 1]
precision, recall, _ = precision_recall_curve(y_test, cat_pred_probs)
cat_pr_auc = auc(recall, precision)

print("CatBoost - Время обучения:", cat_training_time)
print("CatBoost - AUC-PR:", cat_pr_auc)

LightGBM - Время обучения: 1.6441888809204102
LightGBM - AUC-PR: 0.2273658436431587
CatBoost - Время обучения: 25.025012254714966
CatBoost - AUC-PR: 0.2260864034013596

Почему может быть заметная разница в качестве?
Различие в качестве между LightGBM и CatBoost объясняется рядом факторов:

Обработка категориальных признаков: CatBoost лучше справляется с категориальными признаками, так как использует специальный алгоритм, учитывающий порядки и разбиения. В нашем случае мы использовали только вещественные признаки, но CatBoost может применять более сложные техники даже с числовыми данными.

Алгоритмы построения деревьев: LightGBM использует метод Leaf-wise (по листьям), который быстрее, но склонен к переобучению на малых данных. CatBoost применяет Symmetric Tree и более устойчив к переобучению, что помогает в сложных и дисбалансированных задачах.

Обработка дисбаланса классов: CatBoost имеет встроенные методы для работы с дисбалансом классов, что улучшает качество предсказания для менее представленных классов.

Скорость обучения и оптимизация: LightGBM известен своей высокой скоростью благодаря оптимизации построения деревьев и использованию histogram-based подхода. Однако CatBoost может показать лучшие результаты по качеству, так как он применяет особые техники сглаживания и обработки редких значений.

Эти факторы объясняют разницу в показателях качества и скорости обучения между моделями.

__Задание 3. (2 балла)__

Подберите с CV=3 оптимальные параметры алгоритмов, изменяя:

* глубину деревьев;
* количество деревьев;
* темп обучения;
* оптимизируемый функционал.

Проанализируйте соотношения глубины и количества деревьев в зависимости от алгоритма.

Подготовка параметров для подбора

Чтобы определить диапазоны для параметров, создадим сетки гиперпараметров:

* Глубина деревьев (max_depth): определяет, насколько глубокими будут деревья. Более глубокие деревья могут лучше соответствовать данным, но склонны к переобучению.
* Количество деревьев (n_estimators): число деревьев в ансамбле.
* Темп обучения (learning_rate): указывает, с какой скоростью модель обновляет веса для каждого дерева. Низкие значения темпа часто компенсируются большим количеством деревьев.
* Оптимизируемый функционал (objective): функция потерь, используемая при обучении модели.

In [3]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV

X_train_temp = X_train_features
y_train_temp = y_train



# Параметры для подбора
param_grid_lgb = {
    'max_depth': [3, 5, 7],
    'n_estimators': [2, 3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'objective': ['binary', 'cross_entropy']  # Пример для задачи бинарной классификации
}

# Инициализация модели
lgb_model = lgb.LGBMClassifier()

# Кросс-валидация с GridSearchCV
grid_search_lgb = GridSearchCV(estimator=lgb_model, param_grid=param_grid_lgb, cv=3, scoring='average_precision', n_jobs=-1, verbose=1)
grid_search_lgb.fit(X_train_temp, y_train_temp)

# Лучшие параметры и результаты
best_params_lgb = grid_search_lgb.best_params_
best_score_lgb = grid_search_lgb.best_score_

print("Лучшие параметры для LightGBM:", best_params_lgb)
print("Лучшее качество для LightGBM (AUC-PR):", best_score_lgb)

# В данной конфигурации lgb подбирается примерно за минуту+



from catboost import CatBoostClassifier

# Параметры для подбора
param_grid_cat = {
    'depth': [3, 5, 7],
    'iterations': [2, 3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'loss_function': ['Logloss', 'CrossEntropy']  # Пример для бинарной классификации
}

# Инициализация модели
cat_model = CatBoostClassifier(verbose=0)

# Кросс-валидация с GridSearchCV
grid_search_cat = GridSearchCV(estimator=cat_model, param_grid=param_grid_cat, cv=3, scoring='average_precision', n_jobs=-1, verbose=1)
grid_search_cat.fit(X_train_temp, y_train_temp)

# Лучшие параметры и результаты
best_params_cat = grid_search_cat.best_params_
best_score_cat = grid_search_cat.best_score_

print("Лучшие параметры для CatBoost:", best_params_cat)
print("Лучшее качество для CatBoost (AUC-PR):", best_score_cat)

# В данной конфигурации CatBoostClassifier подбирается примерно за пол минуты

Fitting 3 folds for each of 72 candidates, totalling 216 fits
Лучшие параметры для LightGBM: {'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 5, 'objective': 'binary'}
Лучшее качество для LightGBM (AUC-PR): 0.20290773817280616
Fitting 3 folds for each of 72 candidates, totalling 216 fits
Лучшие параметры для CatBoost: {'depth': 5, 'iterations': 5, 'learning_rate': 0.1, 'loss_function': 'Logloss'}
Лучшее качество для CatBoost (AUC-PR): 0.1873292634228948

Анализ соотношения глубины и количест

После выполнения подбора параметров можно проанализировать, как оптимальные значения глубины деревьев и количества деревьев отличаются между LightGBM и CatBoost:

* LightGBM: Часто лучше работает с небольшими значениями глубины деревьев, поскольку его метод построения Leaf-wise с большей глубиной склонен к переобучению. Однако с увеличением n_estimators LightGBM может достичь высоких результатов, используя более мелкие деревья.
* CatBoost: Может эффективно использовать более глубокие деревья благодаря симметричным разбиениям, что снижает риск переобучения и помогает лучше справляться с дисбалансом. Однако для увеличения точности (эквивалент n_estimators) также имеет значение.

__Задание 4. (3.5 балла)__

Добавьте категориальные признаки к вещественным следующими способами:

* как OHE признаки;
* как счетчики со сглаживанием.

При подсчете счетчиков запрещается использование циклов. 

На получившихся датасетах подберите параметры у каждого из алгоритмов. Как меняется время, необходимое для обучения модели в зависимости от способа кодирования? Сравните полученные результаты с встроенными методами обработки категориальных признаков.

In [23]:
import pandas as pd

# Предположим, что данные загружены в датафрейм data и список категориальных признаков известен
categorical_columns = column_category + column_object # Замените на фактические названия категориальных признаков

# Применение OHE к категориальным признакам
X_train_ohe = pd.get_dummies(X_train_full, columns=categorical_columns)
print(np.shape(X_train_ohe))
X_train_ohe.head(1)

X_test_ohe = pd.get_dummies(X_test_full, columns=categorical_columns)
print(np.shape(X_test_ohe))
X_test_ohe.head(1)

(215257, 310)
(92254, 310)

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,TARGET_0,TARGET_1,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,FLAG_OWN_CAR_N,FLAG_OWN_CAR_Y,FLAG_OWN_REALTY_N,FLAG_OWN_REALTY_Y,NAME_TYPE_SUITE_Children,NAME_TYPE_SUITE_Family,NAME_TYPE_SUITE_Group of people,NAME_TYPE_SUITE_Other_A,NAME_TYPE_SUITE_Other_B,"NAME_TYPE_SUITE_Spouse, partner",NAME_TYPE_SUITE_Unaccompanied,NAME_INCOME_TYPE_Businessman,NAME_INCOME_TYPE_Commercial associate,NAME_INCOME_TYPE_Maternity leave,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Student,NAME_INCOME_TYPE_Unemployed,NAME_INCOME_TYPE_Working,NAME_EDUCATION_TYPE_Academic degree,NAME_EDUCATION_TYPE_Higher education,NAME_EDUCATION_TYPE_Incomplete higher,NAME_EDUCATION_TYPE_Lower secondary,NAME_EDUCATION_TYPE_Secondary / secondary special,NAME_FAMILY_STATUS_Civil marriage,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,NAME_FAMILY_STATUS_Single / not married,NAME_FAMILY_STATUS_Unknown,NAME_FAMILY_STATUS_Widow,NAME_HOUSING_TYPE_Co-op apartment,NAME_HOUSING_TYPE_House / apartment,NAME_HOUSING_TYPE_Municipal apartment,NAME_HOUSING_TYPE_Office apartment,NAME_HOUSING_TYPE_Rented apartment,NAME_HOUSING_TYPE_With parents,FLAG_MOBIL_0,FLAG_MOBIL_1,FLAG_EMP_PHONE_0,FLAG_EMP_PHONE_1,FLAG_WORK_PHONE_0,FLAG_WORK_PHONE_1,FLAG_CONT_MOBILE_0,FLAG_CONT_MOBILE_1,FLAG_PHONE_0,FLAG_PHONE_1,FLAG_EMAIL_0,FLAG_EMAIL_1,REGION_RATING_CLIENT_1,REGION_RATING_CLIENT_2,REGION_RATING_CLIENT_3,REGION_RATING_CLIENT_W_CITY_1,REGION_RATING_CLIENT_W_CITY_2,REGION_RATING_CLIENT_W_CITY_3,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,REG_REGION_NOT_LIVE_REGION_0,REG_REGION_NOT_LIVE_REGION_1,REG_REGION_NOT_WORK_REGION_0,REG_REGION_NOT_WORK_REGION_1,LIVE_REGION_NOT_WORK_REGION_0,LIVE_REGION_NOT_WORK_REGION_1,REG_CITY_NOT_LIVE_CITY_0,REG_CITY_NOT_LIVE_CITY_1,REG_CITY_NOT_WORK_CITY_0,REG_CITY_NOT_WORK_CITY_1,LIVE_CITY_NOT_WORK_CITY_0,LIVE_CITY_NOT_WORK_CITY_1,FONDKAPREMONT_MODE_not specified,FONDKAPREMONT_MODE_org spec account,FONDKAPREMONT_MODE_reg oper account,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_block of flats,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes,DEF_60_CNT_SOCIAL_CIRCLE_0.0,DEF_60_CNT_SOCIAL_CIRCLE_1.0,DEF_60_CNT_SOCIAL_CIRCLE_2.0,DEF_60_CNT_SOCIAL_CIRCLE_3.0,DEF_60_CNT_SOCIAL_CIRCLE_4.0,DEF_60_CNT_SOCIAL_CIRCLE_5.0,DEF_60_CNT_SOCIAL_CIRCLE_6.0,DEF_60_CNT_SOCIAL_CIRCLE_7.0,DEF_60_CNT_SOCIAL_CIRCLE_24.0,FLAG_DOCUMENT_2_0,FLAG_DOCUMENT_2_1,FLAG_DOCUMENT_3_0,FLAG_DOCUMENT_3_1,FLAG_DOCUMENT_4_0,FLAG_DOCUMENT_4_1,FLAG_DOCUMENT_5_0,FLAG_DOCUMENT_5_1,FLAG_DOCUMENT_6_0,FLAG_DOCUMENT_6_1,FLAG_DOCUMENT_7_0,FLAG_DOCUMENT_7_1,FLAG_DOCUMENT_8_0,FLAG_DOCUMENT_8_1,FLAG_DOCUMENT_9_0,FLAG_DOCUMENT_9_1,FLAG_DOCUMENT_10_0,FLAG_DOCUMENT_10_1,FLAG_DOCUMENT_11_0,FLAG_DOCUMENT_11_1,FLAG_DOCUMENT_12_0,FLAG_DOCUMENT_12_1,FLAG_DOCUMENT_13_0,FLAG_DOCUMENT_13_1,FLAG_DOCUMENT_14_0,FLAG_DOCUMENT_14_1,FLAG_DOCUMENT_15_0,FLAG_DOCUMENT_15_1,FLAG_DOCUMENT_16_0,FLAG_DOCUMENT_16_1,FLAG_DOCUMENT_17_0,FLAG_DOCUMENT_17_1,FLAG_DOCUMENT_18_0,FLAG_DOCUMENT_18_1,FLAG_DOCUMENT_19_0,FLAG_DOCUMENT_19_1,FLAG_DOCUMENT_20_0,FLAG_DOCUMENT_20_1,FLAG_DOCUMENT_21_0,FLAG_DOCUMENT_21_1,AMT_REQ_CREDIT_BUREAU_HOUR_0.0,AMT_REQ_CREDIT_BUREAU_HOUR_1.0,AMT_REQ_CREDIT_BUREAU_HOUR_2.0,AMT_REQ_CREDIT_BUREAU_HOUR_3.0,AMT_REQ_CREDIT_BUREAU_HOUR_4.0,AMT_REQ_CREDIT_BUREAU_DAY_0.0,AMT_REQ_CREDIT_BUREAU_DAY_1.0,AMT_REQ_CREDIT_BUREAU_DAY_2.0,AMT_REQ_CREDIT_BUREAU_DAY_3.0,AMT_REQ_CREDIT_BUREAU_DAY_4.0,AMT_REQ_CREDIT_BUREAU_DAY_5.0,AMT_REQ_CREDIT_BUREAU_DAY_6.0,AMT_REQ_CREDIT_BUREAU_DAY_8.0,AMT_REQ_CREDIT_BUREAU_DAY_9.0,AMT_REQ_CREDIT_BUREAU_WEEK_0.0,AMT_REQ_CREDIT_BUREAU_WEEK_1.0,AMT_REQ_CREDIT_BUREAU_WEEK_2.0,AMT_REQ_CREDIT_BUREAU_WEEK_3.0,AMT_REQ_CREDIT_BUREAU_WEEK_4.0,AMT_REQ_CREDIT_BUREAU_WEEK_5.0,AMT_REQ_CREDIT_BUREAU_WEEK_6.0,AMT_REQ_CREDIT_BUREAU_WEEK_7.0,AMT_REQ_CREDIT_BUREAU_WEEK_8.0,OCCUPATION_TYPE_Accountants,OCCUPATION_TYPE_Cleaning staff,OCCUPATION_TYPE_Cooking staff,OCCUPATION_TYPE_Core staff,OCCUPATION_TYPE_Drivers,OCCUPATION_TYPE_HR staff,OCCUPATION_TYPE_High skill tech staff,OCCUPATION_TYPE_IT staff,OCCUPATION_TYPE_Laborers,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Realty agents,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Secretaries,OCCUPATION_TYPE_Security staff,OCCUPATION_TYPE_Waiters/barmen staff,ORGANIZATION_TYPE_Advertising,ORGANIZATION_TYPE_Agriculture,ORGANIZATION_TYPE_Bank,ORGANIZATION_TYPE_Business Entity Type 1,ORGANIZATION_TYPE_Business Entity Type 2,ORGANIZATION_TYPE_Business Entity Type 3,ORGANIZATION_TYPE_Cleaning,ORGANIZATION_TYPE_Construction,ORGANIZATION_TYPE_Culture,ORGANIZATION_TYPE_Electricity,ORGANIZATION_TYPE_Emergency,ORGANIZATION_TYPE_Government,ORGANIZATION_TYPE_Hotel,ORGANIZATION_TYPE_Housing,ORGANIZATION_TYPE_Industry: type 1,ORGANIZATION_TYPE_Industry: type 10,ORGANIZATION_TYPE_Industry: type 11,ORGANIZATION_TYPE_Industry: type 12,ORGANIZATION_TYPE_Industry: type 13,ORGANIZATION_TYPE_Industry: type 2,ORGANIZATION_TYPE_Industry: type 3,ORGANIZATION_TYPE_Industry: type 4,ORGANIZATION_TYPE_Industry: type 5,ORGANIZATION_TYPE_Industry: type 6,ORGANIZATION_TYPE_Industry: type 7,ORGANIZATION_TYPE_Industry: type 8,ORGANIZATION_TYPE_Industry: type 9,ORGANIZATION_TYPE_Insurance,ORGANIZATION_TYPE_Kindergarten,ORGANIZATION_TYPE_Legal Services,ORGANIZATION_TYPE_Medicine,ORGANIZATION_TYPE_Military,ORGANIZATION_TYPE_Mobile,ORGANIZATION_TYPE_Other,ORGANIZATION_TYPE_Police,ORGANIZATION_TYPE_Postal,ORGANIZATION_TYPE_Realtor,ORGANIZATION_TYPE_Religion,ORGANIZATION_TYPE_Restaurant,ORGANIZATION_TYPE_School,ORGANIZATION_TYPE_Security,ORGANIZATION_TYPE_Security Ministries,ORGANIZATION_TYPE_Self-employed,ORGANIZATION_TYPE_Services,ORGANIZATION_TYPE_Telecom,ORGANIZATION_TYPE_Trade: type 1,ORGANIZATION_TYPE_Trade: type 2,ORGANIZATION_TYPE_Trade: type 3,ORGANIZATION_TYPE_Trade: type 4,ORGANIZATION_TYPE_Trade: type 5,ORGANIZATION_TYPE_Trade: type 6,ORGANIZATION_TYPE_Trade: type 7,ORGANIZATION_TYPE_Transport: type 1,ORGANIZATION_TYPE_Transport: type 2,ORGANIZATION_TYPE_Transport: type 3,ORGANIZATION_TYPE_Transport: type 4,ORGANIZATION_TYPE_University,ORGANIZATION_TYPE_XNA
42962,0,117000.0,417024.0,20191.5,360000.0,0.020246,-21774,-2125,-4611.0,-4653,12.061091,2.0,13,0.484936,0.18271,0.145543,0.11744,0.088442,0.977735,0.752471,0.044621,0.078942,0.149725,0.226282,0.231894,0.066333,0.100775,0.107399,0.008809,0.028358,0.114231,0.087543,0.977065,0.759637,0.042553,0.07449,0.145193,0.222315,0.228058,0.064958,0.105645,0.105975,0.008076,0.027022,0.11785,0.087955,0.977752,0.755746,0.044595,0.078078,0.149213,0.225897,0.231625,0.067169,0.101954,0.108607,0.008651,0.028236,0.102547,1.0,0.0,1.0,-2008.0,0.0,0.0,3.0,0,1,1,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [27]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV

X_train_temp_ohe = X_train_ohe
y_train_temp = y_train

# Убираем неподдерживаемые символы в названиях столбцов
X_train_temp_ohe.columns = X_train_temp_ohe.columns.str.replace(r'[^\w]', '_', regex=True)


# Параметры для подбора
param_grid_lgb = {
    'max_depth': [3, 5, 7],
    'n_estimators': [2, 3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'objective': ['binary', 'cross_entropy'] # Пример для задачи бинарной классификации
}

# Инициализация модели
lgb_model = lgb.LGBMClassifier()

# Кросс-валидация с GridSearchCV
grid_search_lgb = GridSearchCV(estimator=lgb_model, param_grid=param_grid_lgb, cv=3, scoring='average_precision', n_jobs=-1, verbose=1, error_score='raise')
grid_search_lgb.fit(X_train_temp_ohe, y_train_temp)

# Лучшие параметры и результаты
best_params_lgb = grid_search_lgb.best_params_
best_score_lgb = grid_search_lgb.best_score_

print("Лучшие параметры для LightGBM:", best_params_lgb)
print("Лучшее качество для LightGBM (AUC-PR):", best_score_lgb)



from catboost import CatBoostClassifier

# Параметры для подбора
param_grid_cat = {
    'depth': [3, 5, 7],
    'iterations': [2, 3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'loss_function': ['Logloss', 'CrossEntropy']  # Пример для бинарной классификации
}

# Инициализация модели
cat_model = CatBoostClassifier(verbose=0)

# Кросс-валидация с GridSearchCV
grid_search_cat = GridSearchCV(estimator=cat_model, param_grid=param_grid_cat, cv=3, scoring='average_precision', n_jobs=-1, verbose=1)
grid_search_cat.fit(X_train_temp_ohe, y_train_temp)

# Лучшие параметры и результаты
best_params_cat = grid_search_cat.best_params_
best_score_cat = grid_search_cat.best_score_

print("Лучшие параметры для CatBoost:", best_params_cat)
print("Лучшее качество для CatBoost (AUC-PR):", best_score_cat)

Fitting 3 folds for each of 72 candidates, totalling 216 fits
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Лучшие параметры для LightGBM: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 2, 'objective': 'binary'}
Лучшее качество для LightGBM (AUC-PR): 1.0
Fitting 3 folds for each of 72 candidates, totalling 216 fits
Лучшие параметры для CatBoost: {'depth': 3, 'iterations': 2, 'learning_rate': 0.01, 'loss_function': 'Logloss'}
Лучшее качество для CatBoost (AUC-PR): 1.0

In [31]:
X_test_temp_ohe = X_test_ohe
X_test_temp_ohe.columns = X_test_temp_ohe.columns.str.replace(r'[^\w]', '_', regex=True)

# Инициализация модели
lgb_model_ohe = lgb.LGBMClassifier(verbose=0, learning_rate=0.01, max_depth=3, n_estimators=2, objective='binary')

# Измерение времени обучения
start_time_ohe = time.time()
lgb_model_ohe.fit(X_train_temp_ohe, y_train_temp)
end_time_ohe = time.time()

# Оценка времени
lgb_training_time_ohe = end_time_ohe - start_time_ohe

# Предсказания и оценка качества модели
lgb_pred_probs_ohe = lgb_model_ohe.predict_proba(X_test_temp_ohe)[:, 1]
precision_lgb_ohe, recall_lgb_ohe, _ = precision_recall_curve(y_test, lgb_pred_probs_ohe)
lgb_pr_auc_ohe = auc(recall_lgb_ohe, precision_lgb_ohe)

print("LightGBM - Время обучения:", lgb_training_time_ohe)
print("LightGBM - AUC-PR:", lgb_pr_auc_ohe)



from catboost import CatBoostClassifier

# Инициализация модели
cat_model_ohe = CatBoostClassifier(verbose=False, depth=3, iterations=2, learning_rate=0.01, loss_function='Logloss')

# Измерение времени обучения
start_time = time.time()
cat_model_ohe.fit(X_train_temp_ohe, y_train_temp)
end_time = time.time()

# Оценка времени
cat_training_time_ohe = end_time - start_time

# Предсказания и оценка качества модели
cat_pred_probs_ohe = cat_model_ohe.predict_proba(X_test_temp_ohe)[:, 1]
precision_cat_ohe, recall_cat_ohe, _ = precision_recall_curve(y_test, cat_pred_probs_ohe)
cat_pr_auc_ohe = auc(recall_cat_ohe, precision_cat_ohe)

print("CatBoost - Время обучения:", cat_training_time)
print("CatBoost - AUC-PR:", cat_pr_auc_ohe)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM - Время обучения: 1.4936847686767578
LightGBM - AUC-PR: 1.0
CatBoost - Время обучения: 25.025012254714966
CatBoost - AUC-PR: 1.0

### AUC-PR: 1.0 - такое вообще возможно при непереобученной модели?

__Задание 5. (1 балл)__

Реализуйте блендинг подобранных в предыдущем задании моделей и сравните качество.

### Чисто технически, при AUC-PR: 1.0, блендинг не то чтобы имеет смысл

### Для галочки, достаточно взять результат из предыдущёго задания и сделать комбинированное предсказание с помощью среднего

In [32]:
blended_pred_ohe = (lgb_pred_probs_ohe + cat_pred_probs_ohe) / 2
precision_blended_pred_ohe, recall_blended_pred_ohe, _ = precision_recall_curve(y_test, blended_pred_ohe)
blended_pr_auc_ohe = auc(recall_blended_pred_ohe, precision_blended_pred_ohe)

print("CatBoost - AUC-PR:", blended_pr_auc_ohe)

CatBoost - AUC-PR: 1.0

### На фоне прошлого, не удивительно

__Задание 6. (1.5 балла)__

В задании 3 вы подобрали гиперпараметры для LightGBM и CatBoost на вещественных признаках. Визуализируйте важности признаков, посчитанные этими алгоритмами, в виде горизонтального bar-plot (отсортируйте признаки по убыванию важности, подпишите названия признаков по оси y).

Для каждого из двух алгоритмов удалите неважные признаки (обычно по bar-plot хорошо видно порог на важность, с которого начинается хвост неважных признаков) и обучите ту же модель на получившихся данных. Сильно ли упало качество при удалении признаков, которые модель считает неважными?